# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: gradle test

on:
  # any pull request
  pull_request:
  # any push to master
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  # this test is a heavily modified version of the official gradle test
  # so that it runs each test in parallel and then aggregates the results
  # all in github actions
    get-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Get tests
              run: ./gradlew getTests
            - name: Upload tests
              uses: actions/upload-artifact@v3
              with:
                  name: tests
                  path: tests.txt
    test:
        needs: get-tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                test: ${{ fromJson(needs.get-tests.outputs.tests) }}
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Run tests
              run: ./gradlew test --tests ${{ matrix.test }}

permissions:
  contents: read
